#!/bin/sh

printf '\033[31m ------> THIS IMAGE IS DEPRECATED. USE image adorsys/ci-build inside Gitlab CI OR adorsys/java:8 for runtime,\n ------> DockerHub: https://hub.docker.com/r/adorsys/ci-build/ https://hub.docker.com/r/adorsys/java/ \n ------> Github: https://github.com/adorsys/dockerhub-pipeline-images\033[0m\n'
sleep 600
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

exec /usr/bin/java "$@"
